[package]
name = "stockfighter-skeleton-app-rs"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

[dependencies]

stockfighter-sdk-rs = "0.0.2"
